
// --- CONSTANTES DE DADOS ---
export const rareFursData = {
    "alce": { macho: ["Albino", "Melânico", "Malhado", "Café", "Mosaico", "Acromelanístico"], femea: ["Albino", "Melânico", "Malhado", "Acromelanístico"] },
    "antilocapra": { macho: ["Albino", "Leucismo", "Melânico", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Malhado", "Leucismo", "Melânico"] },
    "antílope_negro": { macho: ["Albino", "Melânico", "Malhado", "Leucismo"], femea: ["Albino", "Melânico", "Malhado", "Leucismo"] },
    "bantengue": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "bisão_das_planícies": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "bisão_europeu": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "búfalo_africano": { macho: ["Albino", "Leucismo"], femea: ["Albino", "Leucismo"] },
    "búfalo_dágua": { macho: ["Albino", "Laranja"], femea: ["Albino", "Laranja"] },
    "cabra_da_montanha": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "cabra_de_leque": { macho: ["Albino"], femea: ["Albino"] },
    "cabra_selvagem": { macho: ["Albino", "Preto", "Cores Mistas Variação 1", "Cores Mistas Variação 2"], femea: ["Albino", "Preto"] },
    "caititu": { macho: ["Albino", "Melânico", "Ochre", "Leucismo"], femea: ["Albino", "Melânico", "Ochre", "Leucismo"] },
    "camurça": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "canguru_cinza_oriental": { macho: ["Albino", "Melânico", "Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3"], femea: ["Albino", "Melânico", "Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3"] },
    "caribu": { macho: ["Albino", "Melânico", "Leucismo","Malhado"], femea: ["Albino", "Melânico", "Leucismo"] },
    "carneiro_azul": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "carneiro_selvagem": { macho: ["Albino", "Malhado Variação 1", "Malhado Variação 2","Leucismo", "Melânico"], femea: ["Albino", "Malhado Variação 1", "Malhado Variação 2","Leucismo", "Melânico"] },
    "cervo_porco_indiano": { macho: ["Malhado", "Leucismo"], femea: ["Malhado", "Leucismo"] },
    "cervo_almiscarado": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "cervo_de_timor": { macho: ["Albino", "Leucismo", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Leucismo"] },
    "cervo_do_pântano": { macho: ["Albino", "Malhado", "Leucismo","Melânico"], femea: ["Albino", "Malhado", "Leucismo","Melânico"] },
    "cervo_sika": { macho: ["Albino", "pintado vermelho"], femea: ["Albino", "pintado vermelho"] },
    "chital": { macho: ["Albino", "Malhado", "Melânico"], femea: ["Albino", "Malhado", "Melânico"] },
    "chacal_listrado": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "codorna_de_restolho": { macho: ["Albino", "Pardo Escuro"], femea: ["Albino"] },
    "codorniz_da_virgínia": { macho: ["Albino"], femea: ["Albino"] },
    "coelho_da_flórida": { macho: ["Albino", "Melânico", "Leucismo Variação 1","Leucismo Variação 2" ], femea: ["Albino", "Melânico", "Leucismo Variação 1","Leucismo Variação 2"] },
    "coelho_europeu": { macho: ["Albino", "Melânico", "Leucismo", "Cinza Claro"], femea: ["Albino", "Melânico", "Leucismo","Cinza Claro"] },
    "coiote": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "corça": { macho: ["Albino", "Melânico", "Malhado Variação 1", "Malhado Variação 2", "Leucismo"], femea: ["Albino", "Melânico", "Malhado", "Leucismo"] },
    "crocodilo_de_água_salgada": { macho: ["Albino", "Melânico", "Pardo Claro", "Malhado Variação 1", "Malhado Variação 2", "Leucismo"], femea: ["Albino", "Melânico", "Pardo Claro", "Malhado Variação 1", "Malhado Variação 2", "Leucismo"] },
    "cudo_menor": { macho: ["Albino", "Melânico"], femea: ["Albino", "Marrom Avermelhado", "Escuro"] },
    "cão_guaxinim": { macho: ["Albino", "Laranja", "Pardo Escuro", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Laranja", "Pardo Escuro", "Malhado Variação 1", "Malhado Variação 2"] },
    "faisão_de_pescoço_anelado": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "frisada": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "galinha_montês": { macho: ["Pálida", "Híbrido", "Escuro"], femea: ["Pálida", "Híbrido", "Escuro"] },
    "galo_lira": { macho: ["Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3", "Melânico Variação 1", "Melânico Variação 2"], femea: ["Laranja", "Ouro"] },
    "gamo": { macho: ["Albino", "Melânico", "Malhado Variação 1", "Malhado Variação 2", "Acromelanística", "Eritrística", "Leucismo " ], femea: ["Albino", "Melânico", "Malhado","Acromelanística", "Eritrística", "Leucismo " ] },
    "ganso_bravo": { macho: ["Híbrido", "Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3", "Leucismo Variação 4", "Leucismo Variação 5"], femea: ["Híbrido", "Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3", "Leucismo Variação 4", "Leucismo Variação 5"] },
    "ganso_campestre_da_tundra": { macho: ["Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3"], femea: ["Leucismo Variação 1", "Leucismo Variação 2", "Leucismo Variação 3"] },
    "ganso_pega": { macho: ["Melânico", "Leucismo Variação 1", "Leucismo Variação 2", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Melânico", "Leucismo Variação 1", "Leucismo Variação 2", "Malhado Variação 1", "Malhado Variação 2"] },
    "ganso_do_canadá": { macho: ["Melânico", "Leucismo Cinza Claro", "Hibrido Branco", "Marrom Hibrido","Albino"], femea: ["Marrom Hibrido", "Melânico", "Leucismo Cinza Claro", "Hibrido Branco", "Albino"] },
    "ganso_das_neves": { macho: ["Albino", "Melânico", "Variação azul", "hibrido", "intermediario"], femea: ["Albino", "Melânico", "Variação azul", "hibrido", "intermediario"] },
    "gnu_de_cauda_preta": { macho: ["Albino"], femea: ["Albino", "Coroado"] },
    "guaxinim_comum": { macho: ["Albino", "Melânico", "Loiro Malhado", "Cinza Malhado"], femea: ["Albino", "Melânico", "Loiro Malhado", "Cinza Malhado"] },
    "iaque_selvagem": { macho: ["Ouro", "Leucismo", "Albino Variação 1", "Albino Variação 2"], femea: ["Ouro", "Leucismo", "Albino Variação 1", "Albino Variação 2", "marrom profundo", "preto profundo"] },
    "ibex_de_beceite": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "jacaré_americano": { macho: ["Albino", "Melânico", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Melânico", "Malhado Variação 1", "Malhado Variação 2"] },
    "javali": { macho: ["Albino", "Melânico", "preto e dourado", "Cinza Roxo"], femea: ["Albino", "Melânico", "preto e dourado", "Cinza Roxo"] },
    "javali_africano": { macho: ["Albino"], femea: ["Albino", "Vermelho"] },
    "lagópode_branco": { macho: ["Branco", "Muda Variação 1", "Muda Variação 2"], femea: ["Branco", "Muda Variação 1", "Muda Variação 2", "mosqueado Variação 1", "mosqueado Variação 2"] },
    "lagópode_escocês": { macho: ["Branco"], femea: ["Branco"] },
    "lebre_antílope": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "lebre_da_eurásia": { macho: ["Albino", "Branco", "Muda Variação 1", "Muda Variação 2", "Pardo Claro", "Pardo Escuro", "Cinza Claro", "Cinza Escuro"], femea: ["Albino", "Branco", "Muda Variação 1", "muda Variação 2"] },
    "lebre_peluda": { macho: ["Albino", "Branco"], femea: ["Albino", "Branco"] },
    "lebre_da_cauda_branca": { macho: ["Albino"], femea: ["Albino"] },
    "lebre_nuca_dourada": { macho: ["Cinza Claro"], femea: ["Cinza Claro"] },
    "lebre_europeia": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "leopardo_das_neves": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "leão": { macho: ["Albino", "Amarelado", "Pardo Escuro"], femea: ["Albino", "Amarelado", "Pardo Escuro"] },
     "lince_pardo": { macho: ["Albino", "Melânico", "Azul"], femea: ["Albino", "Melânico", "Azul"] },
"lince_pardo_do_méxico": { macho: ["Albino", "Melânico", "Azul"], femea: ["Albino", "Melânico", "Azul"] },
    "lince_euroasiática": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "lobo_cinzento": { macho: ["Albino", "Melânico", "Cinza Escuro", "Clara de Ovo", "Pardo Avermelhado", "Acromelanístico", "Carvão Melanístico"], femea: ["Albino", "Melânico", "Cinza Escuro", "Clara de Ovo", "Pardo Avermelhado", "Acromelanístico", "Carvão Melanístico"] },
    "lobo_ibérico": { macho: ["Albino", "Melânico", "Fantasma", "Ogro", "Sombra", "Inverno", "Oliva", "Prístino"], femea: ["Albino", "Melânico", "Inverno", "Oliva", "Prístino"] },
    "marreca_carijó": { macho: ["Melânico"], femea: ["Bege"] },
    "marrequinha_comum": { macho: ["híbrido azul", "híbrido verde", "Leucismo Variação 1", "Leucismo Variação 2"], femea: ["Leucismo"] },
    "marrequinha_americana": { macho: ["Albino", "Verde Claro", "Malhado Variação 1", "Malhado Variação 2", "Malhado Variação 3"], femea: ["Malhado Variação 1", "Malhado Variação 2"] },
    "mouflão_ibérico": { macho: ["Albino", "Melânico", "Cinza"], femea: ["Albino", "Melânico", "Cinza"] },
    "muntíaco_vermelho_do_norte": { macho: ["Albino", "Melânico", "Leucismo Variação 1", "Leucismo Variação 2"], femea: ["Albino", "Melânico", "Leucismo Variação 1", "Leucismo Variação 2"] },
    "nilgó": { macho: ["Malhado Variação 1", "Malhado Variação 2"], femea: ["Malhado Variação 1", "Malhado Variação 2"] },
    "onça_parda": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "órix_do_cabo": { macho: ["Bege", "Escuro", "Ouro"], femea: ["Bege", "Escuro", "Ouro"] },
    "pato_olho_de_ouro": { macho: ["eclipse", "Leucismo Variação 1", "Leucismo Variação 2"], femea: ["Escuro", "Leucismo Variação 1", "Leucismo Variação 2"] },
    "pato_arlequim": { macho: ["Albino", "Melânico"], femea: ["Albino", "Cinza", "Escuro"] },
    "pato_real": { macho: ["Melânico","Leucismo" ], femea: ["Melânico", "amarelado"] },
    "peru_merriami": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "peru_selvagem": { macho: ["Albino", "Melânico", "Leucismo", "bronze"], femea: ["Albino", "Melânico", "Leucismo"] },
    "peru_selvagem_do_rio_grande": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "piadeira": { macho: ["Híbrido", "Eclipse", "Leucismo Variação 1", "Leucismo Variação 2"], femea: ["Leucismo Variação 1", "Leucismo Variação 2"] },
    "porco_selvagem": { macho: ["Albino", "Rosa"], femea: ["Rosa"] },
    "raposa_tibetana": { macho: ["Albino", "Melânico", "Areia", "Esfumaçado", "Leucismo"], femea: ["Albino", "Melânico", "Areia", "Esfumaçado", "Leucismo"] },
    "raposa_cinzenta": { macho: ["Albino", "Melânico", "Leucismo", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Melânico", "Leucismo", "Malhado Variação 1", "Malhado Variação 2"] },
    "raposa_vermelha": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "rena_da_montanha": { macho: ["Albino", "Melânico", "Malhado", "Leucismo"], femea: ["Albino", "Melânico", "Malhado", "Leucismo"] },
    "sambar": { macho: ["Albino", "Leucismo Variação 1", "Leucismo Variação 2", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Malhado", "Leucismo"] },
    "tahr": { macho: ["Albino", "Branco", "Vermelho", "Preto", "Vermelho Escuro", "Pardo Escuro"], femea: ["Albino", "Branco", "Vermelho"] },
    "tetraz_grande": { macho: ["Pálido", "Leucismo"], femea: ["Leucismo"] },
    "tigre_de_bengala": { macho: ["Albino", "Melânico", "Branco", "Branco sem Listras", "Ouro", "Pseudo Melânico Variação 1", "Pseudo Melânico Variação 2", "Pseudo Melânico Branco Variação 1", "Pseudo Melânico Branco Variação 2"], femea: ["Albino", "Melânico", "Branco", "Branco Sem Listras", "Ouro", "Pseudo Melânico Variação 1", "Pseudo Melânico Variação 2", "Pseudo Melânico Branco Variação 1", "Pseudo Melânico Branco Variação 2"] },
    "urso_cinzento": { macho: ["Albino", "Marrom"], femea: ["Albino"] },
    "urso_negro": { macho: ["Amarelado", "Pardo", "Canela"], femea: ["Amarelado", "Pardo", "Canela"] },
    "urso_pardo": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "veado_das_montanhas_rochosas": { macho: ["Albino", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Malhado Variação 1", "Malhado Variação 2"] },
    "veado_de_cauda_branca": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "veado_de_cauda_preta": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "veado_de_roosevelt": { macho: ["Albino", "Melânico", "Malhado"], femea: ["Albino", "Melânico", "Malhado"] },
    "veado_mula": { macho: ["Albino", "Melânico", "Diluído", "Malhado Variação 1", "Malhado Variação 2", "Leucismo","Isabelina Eritrística", "Mosaico","Vermelho Eritrístico" ], femea: ["Albino", "Melânico", "Diluído", "Malhado Variação 1", "Malhado Variação 2", "Leucismo","Isabelina Eritrística", "Mosaico","Vermelho Eritrístico"] },
    "veado_vermelho": { macho: ["Albino", "Melânico", "Malhado Variação 1", "Malhado Variação 2", "Leucismo", "Eritrístico"], femea: ["Albino", "Melânico", "Malhado Variação 1", "Malhado Variação 2", "Leucismo", "Eritrístico"] },
    "zarro_negrinha": { macho: ["Albino", "eclipse", "Leucismo Variação 1", "Leucismo Variação 2"], femea: ["Leucismo Variação 1", "Leucismo Variação 2"] },
    "zarro_castanho": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "ibex_espanhol_do_sudeste": { macho: ["Albino", "Melânico", "laranja", "Cinza Claro", "castanho acinzentado", "marrom hibrido"], femea: ["Albino", "Melânico"] },
    "ibex_de_gredos": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "ibex_de_ronda": { macho: ["Albino", "Melânico"], femea: ["Albino", "Melânico"] },
    "tetraz_azul": { macho: ["Albino", "Melânico", "Leucismo"], femea: ["Albino", "Melânico", "Leucismo"] },
    "marreca_arrebio": { macho: ["Albino", "Melânico", "Malhado", "Leucismo", "Eritristico"], femea: ["Albino", "Melânico", "Leucismo", "Malhado", "Brilhante", "Eritristico"] },
    "pato_carolino": { macho: ["Albino", "Prata Diluída", "Dourado Eritrístico", "Leucísmo", "Melânico", "Malhado"], femea: ["Albino", "Prata Diluída", "Dourado Eritrístico", "Leucísmo", "Melânico", "Malhado"] },
    "castor_norte_americano": { macho: ["Albino", "Melânico", "Leucismo","Malhado"], femea: ["Albino", "Melânico", "Leucismo","Malhado"] },
    "caribu_da_floresta_boreal": { macho: ["Albino", "Melânico", "Leucismo","Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Melânico", "Leucismo", "Malhado Variação 1", "Malhado Variação 2"] },
    "cervo_canadense": { macho: ["Albino", "Melânico", "Leucismo", "Malhado"], femea: ["Albino", "Melânico", "Leucismo", "Malhado"] },
   "tetraz_vermelho": { macho: ["Albino", "Melânico"], femea: ["Leucismo", "Malhado"] }, 
"texugo_europeu": { macho: ["Albino", "Melânico", "Leucismo", "Malhado", "Vermelho Eritrístico Diluído", "Diluído"], femea: ["Albino", "Melânico", "Leucismo", "Malhado", "Vermelho Eritrístico diluído", "Diluído"] },
"galinhola_eurasiática": { macho: ["Albino", "Melânico", "Leucismo", "Pardo Escuro"], femea: ["Albino", "Melânico", "Leucismo", "Pardo Escuro"] },
"vison_americano": { macho: ["Albino", "Melânico", "Leucismo", "Preto", "Malhado Variação 1", "Malhado Variação 2", "Prateado"], femea: ["Albino", "Melânico", "Leucismo", "Preto", "Malhado Variação 1", "Malhado Variação 2", "Prateado"] },
"marta_europeia": { macho: ["Albino", "Melânico", "Leucismo", "Castanho", "Malhado Variação 1", "Malhado Variação 2"], femea: ["Albino", "Melânico", "Leucismo", "Castanho", "Malhado Variação 1", "Malhado Variação 2"] },
 "bisão_da_floresta": { macho: ["Albino", "Melânico", "Leucismo", "Malhado", "Pardo Escuro"], femea: ["Albino", "Melânico", "Leucismo","Malhado","Pardo Escuro"] }
};
export const greatsFursData = { "alce": ["Dois Tons Lendário", "Cinza Lendário", "Bétula lendária", "Carvalho Lendário", "Salpicado Lendário", "Abeto lendário"], "urso_negro": ["Creme Lendário", "Espírito Lendário", "Castanho Lendário", "Pintado Lendário", "Gelo Lendário 2", "Gelo Lendário"], "veado_de_cauda_branca": ["Pardo", "Pardo Escuro", "Bronzeado", "Malhado"], "gamo": ["Café Lendário", "Pintado Lendário", "Dourado Lendário", "Misto Lendário", "Prata Lendário"], "raposa_vermelha": ["Lua de Sangue Lendária", "Bengala Doce Lendária", "Flor de Cerejeira Lendária", "Alcaçuz lendário", "Papoula da Meia Noite Lendária", "Floco de Neve Mística Lendária", "Hortelã-Pimenta Lendária", "Gelo Botão de Rosa Lendária", "Beladona Escarlate Lendária"], "veado_vermelho": ["Pintado Lendário"], "tahr": ["Dourado Lendário", "Cicatrizes Lendárias", "Cinza Lendário", "Café com Leite Lendário", "Crânio Lendário", "Metade Lendária", "Neve Lendário"], "veado_mula": ["Chuva de Gotículas Lendárias", "Via Láctea Lendária", "Sopro de Pétalas Lendário", "Manto Crepuscular Lendário", "Enigma Teia de Aranha Lendário", "Faixas de Canela Lendário"], "faisão_de_pescoço_anelado": ["Rubi Lendário", "Pérola Lendário", "Granada Lendário", "Safira Lendário", "Obsidiana Lendário", "Citrino Lendário", "Esmeralda Lendário", "Morganita Lendário"], "lobo_cinzento": ["Congelado Lendário", "Esqueleto Lendário", "Vento Cortante Lendário", "Corneta de Batalha Lendário", "Cicatriz Lendário", "Vanguarda Lendário", "Duas-Almas Lendário", "Amanhecer Lendário","Oco Lendário"],"Corça": ["Véu-Fantasma Lendário", "Alvorada Lendário", "Véu De Ferrugem Lendário", "Marca da Lua Lendário", "Enevoado Lendário"], "javali": ["Retalho Lendário", "Ardente Lendário", "Caramelo Lendário", "Queimado Lendário", "Malhado Lendário", "Pintado Lendário", "Cinzento Lendário", "Giz Lendário","Carvão Lendário"] };

export const items = ["Alce","Antilocapra","Antílope Negro","Bantengue","Bisão da Floresta","Bisão das Planícies","Bisão Europeu","Búfalo Africano","Búfalo D'Água","Cabra da Montanha","Cabra de Leque","Cabra Selvagem","Caititu","Camurça","Canguru-Cinza Oriental", "Chacal Listrado", "Caribu","Caribu da Floresta Boreal","Carneiro Azul","Carneiro Selvagem","Castor Norte-Americano","Cervo Almiscarado","Cervo Canadense","Cervo do Pântano","Cervo de Timor","Cervo Sika","Cervo-porco Indiano","Chital","Codorna-de-restolho","Codorniz da Virgínia","Coelho da Flórida","Coelho Europeu","Coiote","Corça","Crocodilo de Água Salgada","Cudo Menor","Faisão de Pescoço Anelado","Frisada", "Galinhola Eurasiática", "Galo Lira","Gamo","Ganso Bravo","Ganso Campestre da Tundra","Ganso das Neves","Ganso do Canadá","Ganso Pega","Gnu de Cauda Preta","Guaxinim Comum","Iaque Selvagem","Ibex de Beceite","Ibex de Gredos","Ibex de Ronda","Ibex Espanhol do Sudeste","Jacaré Americano","Javali","Javali Africano", "Lebre Europeia", "Lebre-antílope","Lebre-da-cauda-branca","Lebre Da Eurásia","Lebre Nuca Dourada","Lebre Peluda","Leão","Leopardo das Neves","Lince Euroasiática","Lince Pardo do México", "Lince Pardo", "Lobo Cinzento","Lobo Ibérico","Marreca Arrebio","Marreca Carijó","Marrequinha Americana","Marrequinha Comum","Mouflão Ibérico", "Marta Europeia", "Muntíaco Vermelho do Norte","Nilgó","Onça Parda","Órix do Cabo","Pato Carolino","Pato Arlequim","Pato Olho de Ouro","Pato Real","Peru Merriami","Peru Selvagem","Peru Selvagem do Rio Grande","Piadeira","Porco Selvagem","Raposa cinzenta","Raposa tibetana","Raposa Vermelha","Rena da Montanha","Sambar","Tahr", "Texugo Europeu", "Tetraz Azul", "Tetraz Vermelho","Tetraz Grande","Tigre-de-Bengala","Urso Cinzento","Urso Negro","Urso Pardo","Veado das Montanhas Rochosas","Veado de Cauda Branca","Veado de Cauda Preta","Veado-Mula", "Vison Americano", "Veado de Roosevelt","Veado Vermelho","Cão Guaxinim","Lagópode-Branco","Lagópode-Escocês","Galinha-Montês","Zarro-Negrinha","Zarro-castanho"];

export const diamondFursData = {
     "alce": { macho: ["Bronzeado", "Pardo", "Pardo Claro"], femea: [] },
    "antilocapra": { macho: ["Bronzeado", "Escuro", "Pardo"], femea: [] },
    "antílope_negro": { macho: ["Escuro", "Pardo Escuro", "Preto", "Bege"], femea: [] },
    "bantengue": { macho: ["Preto", "Café", "Pardo", "Pardo Escuro"], femea: [] },
    "bisão_da_floresta": { macho: ["Pardo Escuro", "Ruivo", "Metade Ruivo", "Pardo Claro"], femea: [] },
    "bisão_das_planícies": { macho: ["Escuro", "Cinza Claro", "Pardo", "Pardo Claro"], femea: [] },
    "bisão_europeu": { macho: ["Pardo", "Pardo Claro", "Pardo Escuro"], femea: [] },
    "búfalo_dágua": { macho: ["Cinzento", "Preto", "Laranja"], femea: [] },
    "búfalo_africano": { macho: ["Cinzento", "Pardo", "Preto"], femea: [] },
    "cabra_da_montanha": { macho: ["Bege", "Branco", "Cinza Claro", "Pardo Claro"], femea: [] },
    "cabra_de_leque": { macho: ["Bronzeado", "Laranja", "Pardo Escuro"], femea: [] },
    "cabra_selvagem": { macho: ["Amarelado", "Branco", "Pardo e Branco", "Pardo Negro", "Preto e Branco", "Pardo"], femea: [] },
    "caititu": { macho: ["Cinza Escuro", "Cinzento", "Pardo", "Pardo Escuro"], femea: [] },
    "camurça": { macho: ["Cor de Mel", "Pardo", "Pardo e Cinza", "Pardo Escuro"], femea: [] },
    "canguru_cinza_oriental": { macho: ["Cinzento Variação 1", "Cinzento Variação 2","Pardo e Cinza", "Pardo Variação 1", "Pardo Variação 2"], femea: [] },
    "caribu": { macho: ["Pardo Claro", "Pardo Escuro"], femea: [] },
    "caribu_da_floresta_boreal": { macho: ["Pardo Escuro", "Pardo Claro"], femea: [] },
    "carneiro_azul": { macho: ["Cinza Ardósia", "Pardo", "Cinza Azulado", "Amarelo"], femea: [] },
    "carneiro_selvagem": { macho: ["Preto", "Pardo", "Cinzento", "Bronze"], femea: [] },
    "castor_norte_americano": { macho: [], femea: ["Pardo Escuro", "Pardo Claro", "Marrom Avermelhado"] },
    "cervo_almiscarado": { macho: ["Pardo e Cinza", "Pardo Escuro"], femea: [] },
    "cervo_canadense": { macho: ["Juba Marrom", "Escuro", "Malhado"], femea: ["Malhado"] },
    "cervo_do_pântano": { macho: ["Pardo", "Pardo Claro", "Vermelho", "Pardo Escuro", "Vermelho Escuro"], femea: [] },
    "cervo_de_timor": { macho: ["Dois Tons", "Pardo", "Pardo Claro", "Pardo e Branco"], femea: [] },
    "cervo_sika": { macho: ["Escuro e Pintado", "Pardo", "Pintado", "Preto"], femea: [] },
    "cervo_porco_indiano": { macho: ["Pardo", "Escuro e Pintado", "Pardo Escuro", "Pintado"], femea: [] },
    "chital": { macho: ["Pintado", "Escuro"], femea: [] },
    "chacal_listrado": { macho: ["Pardo Claro", "Pardo Cinza", "Cinzento"], femea: [] },
    "codorna_de_restolho": { macho: ["Pardo", "Pardo e Cinza", "Pardo Escuro"], femea: [] },
    "codorniz_da_virgínia": { macho: [], femea: ["Pardo"] },
    "coelho_da_flórida": { macho: [], femea: ["Pardo", "Pardo Claro", "Cinzento", "Cinza Claro"] },
    "coelho_europeu": { macho: ["Bronzeado", "Pardo", "Pardo Claro", "Pardo Escuro"], femea: [] },
    "coiote": { macho: ["Cinza Escuro", "Pardo e Cinza", "Laranja"], femea: [] },
    "corça": { macho: ["Cinza Escuro", "Pardo", "Pardo Escuro"], femea: [] },
    "crocodilo_de_água_salgada": { macho: ["Cinzento", "Oliva", "Pardo Escuro"], femea: [] },
    "cudo_menor": { macho: ["Cinzento"], femea: [] },
    "cão_guaxinim": { macho: ["Cinzento", "Pardo Claro", "Preto e Branco"], femea: [] },
    "faisão_de_pescoço_anelado": { macho: ["Cinzento", "Muda", "Pardo", "Pardo e Branco"], femea: [] },
    "frisada": { macho: ["Cinzento", "Plum. de Inverno"], femea: [] },
    "galinha_montês": { macho: ["Cinzento", "Escuro", "Pardo", "Pardo Claro"], femea: [] },
    "galo_lira": { macho: ["Escuro"], femea: [] },
    "galinhola_eurasiática": { macho: ["Pardo", "Cinza"], femea: ["Pardo", "Cinza"] },
    "gamo": { macho: ["Escuro", "Escuro e Pintado", "Pintado", "Branco", "Chocolate"], femea: [] },
    "ganso_bravo": { macho: ["Pardo", "Cinzento"], femea: [] },
    "ganso_campestre_da_tundra": { macho: ["Cinza Claro", "Cinza Escuro", "Pardo"], femea: [] },
    "ganso_das_neves": { macho: ["Variação Branca"], femea: [] },
    "ganso_do_canadá": { macho: ["Marrom Híbrido", "Pardo e Cinza"], femea: [] },
    "ganso_pega": { macho: ["Amarelo", "Bordô", "Laranja"], femea: [] },
    "gnu_de_cauda_preta": { macho: ["Cinzento", "Cinza Escuro", "Ouro"], femea: [] },
    "guaxinim_comum": { macho: ["Amarelado", "Cinzento", "Pardo"], femea: [] },
    "iaque_selvagem": { macho: ["Pardo Escuro", "Vermelho Escuro","Vermelho Escuro Lendário", "Preto Profundo", "Marrom Profundo"], femea: [] },
    "ibex_de_beceite": { macho: ["Cinzento", "Marrom Híbrido", "Laranja", "Pardo e Cinza"], femea: [] },
    "jacaré_americano": { macho: ["Pardo Escuro", "Oliva"], femea: [] },
    "lagópode_branco": { macho: ["Muda Variação 1", "Muda Variação 2", "Bicolor"], femea: [] },
    "lagópode_escocês": { macho: ["Muda", "Bicolor"], femea: [] },  
    "javali": { macho: ["Pardo Variação 1", "Pardo Variação 2", "Pardo Claro ", "Pardo Escuro"], femea: [] },
    "javali_africano": { macho: ["Pardo Avermelhado", "Cinzento Escuro", "Escuro"], femea: [] },
    "lebre_antílope": { macho: ["Mosqueado", "Cinzento", "Pardo Escuro", "Pardo"], femea: [] },
    "lebre_da_cauda_branca": { macho: ["Bege", "Cinzento", "Pardo", "Pardo Claro"], femea: [] },
    "lebre_da_eurásia": { macho: ["Cinza Claro", "Cinza Escuro", "Pardo Claro", "Pardo Escuro"], femea: ["Cinza Claro", "Cinza Escuro", "Pardo Claro", "Pardo Escuro"] },
    "lebre_europeia": { macho: [], femea: ["Cinza", "Pardo", "Escuro", "Pardo Claro"] },
    "lebre_nuca_dourada": { macho: [], femea: ["Castanho", "Pardo", "Cinzento"] },
    "lebre_peluda": { macho: ["Cinza Claro", "Pardo Claro", "Pardo Escuro", "Muda"], femea: ["Cinza Claro", "Pardo Claro", "Pardo Escuro", "Muda"] },
    "leão": { macho: ["Bronzeado", "Pardo Claro"], femea: [] },
    "leopardo_das_neves": { macho: ["Neve", "Caramelo"], femea: [] },
    "lince_euroasiática": { macho: ["Cinzento", "Pardo Claro"], femea: [] },
    "lince_pardo_do_méxico": { macho: ["Bronzeado", "Cinzento", "Pardo", "Vermelho"], femea: [] },
    "lince_pardo": { macho: ["Bronzeado", "Cinzento", "Pardo", "Vermelho"], femea: [] },
    "lobo_cinzento": { macho: ["Cinzento", "Pardo"], femea: [] },
    "lobo_ibérico": { macho: ["Cinzento", "Pardo e Cinza"], femea: [] },
    "marreca_arrebio": { macho: ["Eclipse", "Cinza", "Eritrístico"], femea: [] },
    "marreca_carijó": { macho: ["Canela", "Vermelho", "Malhado"], femea: [] },
    "marta_europeia": { macho: ["Pardo", "Pardo Claro", "Preto"], femea: [] },
    "marrequinha_comum": { macho: ["Verde Escuro", "Verde Claro"], femea: [] },
    "marrequinha_americana": { macho: [ "Verde Claro"], femea: [] },
    "mouflão_ibérico": { macho: ["Pardo Claro", "Pardo"], femea: [] },
    "muntíaco_vermelho_do_norte": { macho: [ "Vermelho Variação 1", "Vermelho Variação 2"], femea: [] },
    "nilgó": { macho: ["Azul", "Pardo Escuro"], femea: [] },
    "onça_parda": { macho: ["Cinzento", "Vermelho Escuro", "Pardo Claro"], femea: [] },
    "órix_do_cabo": { macho: ["Cinzento", "Cinza Claro"], femea: ["Cinzento", "Cinza Claro"] },
    "pato_olho_de_ouro": { macho: ["Preto"], femea: [] },
    "pato_arlequim": { macho: ["Malhado", "Cinza Escuro"], femea: [] },
    "pato_real": { macho: ["Pardo Negro","Marrom Híbrido", "Malhado"], femea: [] },
    "peru_merriami": { macho: ["Pardo", "Pardo Escuro", "Pardo Claro"], femea: [] },
    "peru_selvagem": { macho: ["Pardo Claro", "Bronze", "Pardo"], femea: [] },
    "peru_selvagem_do_rio_grande": { macho: ["Pardo", "Siena", "Siena Claro","Pardo Claro"], femea: [] },
    "piadeira": { macho: ["Pardo", "Cinzento"], femea: [] },
    "porco_selvagem": { macho: [ "Preto", "Preto e Dourado", "Manchas Pretas Variação 1", "Manchas Pretas Variação 2", "Hibrido Marrom Variação 1", "Hibrido Marrom Variação 2", "Marrom Escuro Variação 1", "Marrom Escuro Variação 2"], femea: [] },
    "raposa_tibetana": { macho: ["Vermelho", "Pardo", "Laranja", "Cinzento"], femea: [] },
    "raposa_cinzenta": { macho: ["Vermelho", "Dois Tons","Cinzento"], femea: ["Vermelho", "Dois Tons","Cinzento"] },
    "raposa_vermelha": { macho: ["Vermelho", "Vermelho Escuro", "Laranja"], femea: [] },
    "rena_da_montanha": { macho: ["Pardo Escuro", "Pardo Claro"], femea: [] },
    "sambar": { macho: ["Pardo", "Pardo Escuro", "Pardo Claro", "Gradiente Escuro"], femea: [] },
    "tahr": { macho: ["Pardo Claro", "Palha", "Pardo Avermelhado"], femea: [] },
    "tetraz_grande": { macho: ["Escuro"], femea: [] },
    "texugo_europeu": { macho: ["Cinza Escuro", "Cinza", "Pardo", "Diluido"], femea: [] },
    "tetraz_vermelho": { macho: ["Vermelho", "Vermelho Escuro"], femea: [] },
    "tigre_de_bengala": { macho: ["Laranja"], femea: [] },
    "urso_cinzento": { macho: ["Pardo e Cinza"], femea: [] },
    "urso_negro": { macho: ["Preto", "Escuro", "Cinzento"], femea: [] },
    "urso_pardo": { macho: ["Espírito", "Cinza", "Pardo Avermelhado", "Ouro", "Pardo Claro", "Pardo Escuro", "Amarelo", "Canela"], femea: [] },
    "veado_das_montanhas_rochosas": { macho: ["Pardo", "Pardo Claro"], femea: [] },
    "veado_de_cauda_branca": { macho: ["Pardo", "Pardo Escuro", "Bronzeado"], femea: [] },
    "veado_de_cauda_preta": { macho: ["Pardo e Cinza", "Cinzento", "Cinza Escuro"], femea: [] },
    "veado_de_roosevelt": { macho: ["Pardo", "Laranja", "Bronzeado"], femea: [] },
    "vison_americano": { macho: ["Pardo Escuro", "Pardo"], femea: [] },
    "veado_mula": { macho: ["Pardo", "Cinzento", "Amarelado"], femea: [] },
    "veado_vermelho": { macho: ["Pardo Escuro", "Pardo Claro", "Pardo"], femea: [] },
    "zarro_negrinha": { macho: ["Preto"], femea: [] },
    "zarro_castanho": { macho: ["Pardo Escuro", "Pardo Avermelhado"], femea: [] },
    "ibex_espanhol_do_sudeste": { macho: ["Pardo", "Marrom Hibrido", "Pardo Hibrido",  "Castanho Acinzentado", "Cinza Claro", "Laranja"], femea: [] },
    "ibex_de_gredos": { macho: ["Pardo e Cinza", "Marrom Hibrido", "Cinza Claro", "Cinzento"], femea: [] },
    "ibex_de_ronda": { macho: ["Pardo", "Pardo e Cinza", "Marrom Hibrido", "Cinzento"], femea: [] },
    "tetraz_azul": { macho: ["Pardo", "Muda", "Cinza Ardósia"], femea: [] },
    "marreca_arrebio": { macho: ["Eclipse", "Cinza"], femea: [] },
    "pato_carolino": { macho: ["Escuro", "Padrão"], femea: [] },
    "castor_norte_americano": { macho: [], femea: ["Pardo Escuro", "Pardo Claro", "Marrom Avermelhado"] },
    "caribu_da_floresta_boreal": { macho: ["Pardo Escuro", "Pardo Claro"], femea: [] },
    "cervo_canadense": { macho: ["Escuro", "Juba Marrom"], femea: [] },
    "bisão_da_floresta": { macho: ["Ruivo", "Pardo Claro", "Metade Ruivo"], femea: [] }
};
export const reservesData = { layton_lake: { name: "Layton Lake", image: "reservas/layton_lake.png", animals: ["alce", "veado_de_cauda_branca", "veado_de_cauda_preta", "veado_de_roosevelt", "urso_negro", "coiote", "pato_real", "lebre_da_cauda_branca", "peru_merriami"] }, hirschfelden: { name: "Hirschfelden", image: "reservas/hirschfelden.png", animals: ["gamo", "corça", "veado_vermelho", "javali", "bisão_europeu", "raposa_vermelha", "ganso_do_canadá", "coelho_europeu", "faisão_de_pescoço_anelado"] }, medved_taiga: { name: "Medved Taiga", image: "reservas/medved_taiga.png", animals: ["alce", "rena_da_montanha", "tetraz_grande", "cervo_almiscarado", "urso_pardo", "javali", "lince_euroasiática", "lobo_cinzento"] }, vurhonga_savanna: { name: "Vurhonga Savana", image: "reservas/vurhonga_savanna.png", animals: ["chacal_listrado", "lebre_nuca_dourada", "piadeira", "cudo_menor", "cabra_de_leque", "javali_africano", "gnu_de_cauda_preta", "búfalo_africano", "leão", "órix_do_cabo"] }, parque_fernando: { name: "Parque Fernando", image: "reservas/parque_fernando.png", animals: ["veado_vermelho", "marreca_carijó", "caititu", "veado_mula", "onça_parda", "antílope_negro", "búfalo_dágua", "chital"] }, yukon_valley: { name: "Yukon Valley", image: "reservas/yukon_valley.png", animals: ["caribu", "ganso_do_canadá", "alce", "urso_cinzento", "lobo_cinzento", "bisão_das_planícies", "raposa_vermelha", "pato_arlequim"] }, cuatro_colinas: { name: "Cuatro Colinas", image: "reservas/cuatro_colinas.png", animals: ["ibex_de_gredos", "faisão_de_pescoço_anelado", "ibex_de_beceite", "ibex_espanhol_do_sudeste", "ibex_de_ronda", "mouflão_ibérico", "lobo_ibérico", "javali", "corça", "lebre_europeia", "veado_vermelho"] }, silver_ridge_peaks: { name: "Silver Ridge Peaks", image: "reservas/silver_ridge_peaks.png", animals: ["antilocapra", "carneiro_selvagem", "bisão_das_planícies", "cabra_da_montanha", "veado_mula", "onça_parda", "urso_negro", "veado_das_montanhas_rochosas", "peru_merriami"] }, te_awaroa: { name: "Te Awaroa", image: "reservas/te_awaroa.png", animals: ["veado_vermelho","gamo", "cabra_selvagem", "porco_selvagem", "cervo_sika", "tahr", "peru_merriami", "camurça", "coelho_europeu", "pato_real"] }, rancho_del_arroyo: { name: "Rancho del Arroyo", image: "reservas/rancho_del_arroyo.png", animals: ["veado_mula", "veado_de_cauda_branca", "carneiro_selvagem", "antilocapra", "caititu", "coiote", "lince_pardo_do_méxico", "peru_selvagem_do_rio_grande", "faisão_de_pescoço_anelado", "lebre_antílope"] }, mississippi_acres: { name: "Mississippi Acres", image: "reservas/mississippi_acres.png", animals: ["veado_de_cauda_branca", "codorniz_da_virgínia", "marrequinha_americana", "peru_selvagem", "porco_selvagem", "urso_negro", "raposa_cinzenta", "guaxinim_comum", "coelho_da_flórida", "jacaré_americano"] }, revontuli_coast: { name: "Costa de Revontuli", image: "reservas/revontuli_coast.png", animals: ["galinha_montês", "veado_de_cauda_branca", "urso_pardo", "alce", "ganso_bravo", "ganso_campestre_da_tundra", "ganso_do_canadá", "lagópode_branco", "lagópode_escocês", "pato_real", "piadeira", "tetraz_grande", "cão_guaxinim", "lince_euroasiática", "galo_lira", "lebre_da_eurásia", "marrequinha_comum", "pato_olho_de_ouro", "zarro_negrinha"] }, new_england_mountains: { name: "New England Mountains", image: "reservas/new_england_mountains.png", animals: ["alce", "codorniz_da_virgínia", "coelho_da_flórida", "faisão_de_pescoço_anelado", "marrequinha_americana", "pato_olho_de_ouro", "pato_real", "peru_selvagem", "guaxinim_comum", "lince_pardo", "raposa_cinzenta", "veado_de_cauda_branca", "urso_negro", "coiote", "raposa_vermelha", "gamo"] }, emerald_coast: { name: "Emerald Coast", image: "reservas/emerald_coast.png", animals: ["canguru_cinza_oriental", "codorna_de_restolho", "raposa_vermelha", "cabra_selvagem", "cervo_porco_indiano", "porco_selvagem", "veado_vermelho", "sambar", "cervo_de_timor", "gamo", "bantengue", "crocodilo_de_água_salgada", "ganso_pega", "chital"] }, sundarpatan: { name: "Sundarpatan", image: "reservas/sundarpatan.png", animals: ["antílope_negro", "ganso_bravo","lebre_peluda", "muntíaco_vermelho_do_norte", "raposa_tibetana", "tahr", "carneiro_azul", "cervo_do_pântano", "nilgó", "búfalo_dágua", "leopardo_das_neves", "iaque_selvagem", "tigre_de_bengala"] }, salzwiesen: { name: "Salzwiesen Park", image: "reservas/salzwiesen.png", animals: ["coelho_europeu", "frisada", "galo_lira", "guaxinim_comum", "raposa_vermelha", "ganso_campestre_da_tundra", "faisão_de_pescoço_anelado", "cão_guaxinim", "ganso_bravo", "marrequinha_comum", "pato_olho_de_ouro", "pato_real", "piadeira", "zarro_negrinha", "zarro_castanho"] }, askiy_ridge: { name: "Askiy Ridge", image: "reservas/askiy_ridge.png", animals: ["alce", "caribu_da_floresta_boreal", "urso_negro", "veado_mula", "bisão_da_floresta", "cabra_da_montanha", "antilocapra", "tetraz_azul", "pato_real", "pato_carolino", "marreca_arrebio", "ganso_do_canadá", "ganso_das_neves", "lobo_cinzento", "cervo_canadense", "veado_de_cauda_branca", "faisão_de_pescoço_anelado", "carneiro_selvagem", "castor_norte_americano"] }, torr_nan_sithean: { name: "Tórr Nan Síthean", image: "reservas/torr_nan_sithean_logo.png", animals: ["corça", "cabra_selvagem", "raposa_vermelha", "gamo", "cervo_sika", "javali", "texugo_europeu", "vison_americano", "marta_europeia", "galinhola_eurasiática", "piadeira", "faisão_de_pescoço_anelado","tetraz_grande","lebre_da_eurásia", "galo_lira", "veado_vermelho", "tetraz_vermelho"] }};

// NOVO: Dados dos Hotspots por Reserva e Animal
export const animalHotspotData = {
     "layton_lake": {
        "alce": { maxScore: "274.99", maxWeightEstimate: "545-620 KG", drinkZonesPotential: "12:00 - 16:00", animalClass: "8", maxLevel: "5 (Médio)" },
        "veado_de_cauda_branca": { maxScore: "255.09", maxWeightEstimate: "75-100 KG", drinkZonesPotential: "08:00 - 12:00", animalClass: "4", maxLevel: "3 (Muito Fácil)" },
        "veado_de_cauda_preta": { maxScore: "177.58", maxWeightEstimate: "81-95 KG", drinkZonesPotential: "16:00 - 20:00", animalClass: "4", maxLevel: "5 (Médio)" },
        "veado_de_roosevelt": { maxScore: "380.84", maxWeightEstimate: "450-500 KG", drinkZonesPotential: "04:00 - 08:00", animalClass: "7", maxLevel: "5 (Médio)" },
        "urso_negro": { maxScore: "22.8", maxWeightEstimate: "227-290 KG", drinkZonesPotential: "04:00 - 08:00", animalClass: "7", maxLevel: "9 (Lendário)" },
        "coiote": { maxScore: "56.87", maxWeightEstimate: "24-27 KG", drinkZonesPotential: "00:00 - 04:00", animalClass: "2", maxLevel: "9 (Lendário)" },
        "pato_real": { maxScore: "19.61", maxWeightEstimate: "1-2 KG", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "3 (Muito Fácil)" },
        "lebre_da_cauda_branca": { maxScore: "6.33", maxWeightEstimate: "5-6 KG", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "3 (Muito Fácil)" },
        "peru_merriami": { maxScore: "4.62", maxWeightEstimate: "9-11 KG", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "3 (Muito Fácil)" }
    },
    "hirschfelden": {
        "gamo": { maxScore: "249.99", maxWeightEstimate: "82-100 KG", drinkZonesPotential: "10:00-13:00", animalClass: "4", maxLevel: "5 (Médio)" },
        "corça": { maxScore: "81.86", maxWeightEstimate: "29-35 KG", drinkZonesPotential: "14:00-17:00", animalClass: "3", maxLevel: "3 (Muito Fácil)" },
        "veado_vermelho": { maxScore: "251.07", maxWeightEstimate: "210-240 KG", drinkZonesPotential: "06:00-10:00", animalClass: "6", maxLevel: "9 (Lendário)" },
        "javali": { maxScore: "144.25", maxWeightEstimate: "186-240 KG", drinkZonesPotential: "00:00-03:00", animalClass: "5", maxLevel: "5 (Médio)" },
        "bisão_europeu": { maxScore: "127.62", maxWeightEstimate: "765-920 KG", drinkZonesPotential: "10:00-14:00", animalClass: "9", maxLevel: "5 (Médio)" },
        "raposa_vermelha": { maxScore: "14.05", maxWeightEstimate: "12-15 KG", drinkZonesPotential: "17:00-20:00", animalClass: "2", maxLevel: "9 (Lendário)" },
        "ganso_do_canadá": { maxScore: "8.59", maxWeightEstimate: "8-9 KG", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "5 (Médio)" },
        "coelho_europeu": { maxScore: "2.42", maxWeightEstimate: "2 KG", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "3 (Muito Fácil)" },
        "faisão_de_pescoço_anelado": { maxScore: "20.29", maxWeightEstimate: "2-3 kg", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "3 (Muito Fácil)"}
    },
 "revontuli_coast": {
    "galinha_montês": { "maxScore": "435", "maxWeightEstimate": "0.41-0.45 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "veado_de_cauda_branca": { "maxScore": "255.09", "maxWeightEstimate": "75-100 KG", "drinkZonesPotential": "08:00 - 12:00", "animalClass": "4", "maxLevel": "3 (Muito Fácil)" },
    "urso_pardo": { "maxScore": "27.7", "maxWeightEstimate": "389-452 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "alce": { "maxScore": "274.99", "maxWeightEstimate": "545-620 KG", "drinkZonesPotential": "12:00 - 16:00", "animalClass": "8", "maxLevel": "5 (Médio)" },
    "ganso_bravo": { "maxScore": "3.85", "maxWeightEstimate": "3-4 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "ganso_campestre_da_tundra": { "maxScore": "3.16", "maxWeightEstimate": "2-3 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "ganso_do_canadá": { "maxScore": "8.59", "maxWeightEstimate": "8-9 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "lagópode_branco": { "maxScore": "709", "maxWeightEstimate": "0.66-0.74 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "lagópode_escocês": { "maxScore": "772", "maxWeightEstimate": "0.72-0.81 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_real": { "maxScore": "19.61", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "piadeira": { "maxScore": "905", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "tetraz_grande": { "maxScore": "4.64", "maxWeightEstimate": "4-5 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "cão_guaxinim": { "maxScore": "9.29", "maxWeightEstimate": "8-10 kg", "drinkZonesPotential": "10:00-13:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "lince_euroasiática": { "maxScore": "27.68", "maxWeightEstimate": "35-45 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "3", "maxLevel": "9 (Lendário)" },
    "galo_lira": { "maxScore": "120", "maxWeightEstimate": "0-1 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "lebre_da_eurásia": { "maxScore": "5.6", "maxWeightEstimate": "5-6 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "marrequinha_comum": { "maxScore": "354", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_olho_de_ouro": { "maxScore": "1230", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "zarro_negrinha": { "maxScore": "963", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" }
},
"cuatro_colinas": {
    "ibex_de_gredos": { "maxScore": "100.17", "maxWeightEstimate": "85-102 KG", "drinkZonesPotential": "10:00-14:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "faisão_de_pescoço_anelado": { "maxScore": "20.29", "maxWeightEstimate": "2-3 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "ibex_de_beceite": { "maxScore": "191.63", "maxWeightEstimate": "91-110 KG", "drinkZonesPotential": "10:00-14:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "ibex_espanhol_do_sudeste": { "maxScore": "89.68", "maxWeightEstimate": "74-87 KG", "drinkZonesPotential": "10:00-14:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "ibex_de_ronda": { "maxScore": "107.98", "maxWeightEstimate": "61-70 KG", "drinkZonesPotential": "10:00-14:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "mouflão_ibérico": { "maxScore": "179.56", "maxWeightEstimate": "52-60 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "lobo_ibérico": { "maxScore": "39", "maxWeightEstimate": "45-50 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "5", "maxLevel": "9 (Lendário)" },
    "javali": { "maxScore": "144.25", "maxWeightEstimate": "186-240 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "corça": { "maxScore": "81.86", "maxWeightEstimate": "29-35 KG", "drinkZonesPotential": "14:00-17:00", "animalClass": "3", "maxLevel": "3 (Muito Fácil)" },
    "lebre_europeia": { "maxScore": "6.5", "maxWeightEstimate": "5-7 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "veado_vermelho": { "maxScore": "251.07", "maxWeightEstimate": "210-240 KG", "drinkZonesPotential": "06:00-10:00", "animalClass": "6", "maxLevel": "9 (Lendário)" }
},
"emerald_coast": {
    "canguru_cinza_oriental": { "maxScore": "492", "maxWeightEstimate": "53-66 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "4", "maxLevel": "9 (Lendário)" },
    "codorna_de_restolho": { "maxScore": "238", "maxWeightEstimate": "0.12-0.13 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "raposa_vermelha": { "maxScore": "14.05", "maxWeightEstimate": "12-15 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "cabra_selvagem": { "maxScore": "208.71", "maxWeightEstimate": "43-50 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "cervo_porco_indiano": { "maxScore": "108.68", "maxWeightEstimate": "43-50 KG", "drinkZonesPotential": "13:00-17:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "porco_selvagem": { "maxScore": "144.25", "maxWeightEstimate": "161-205 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "veado_vermelho": { "maxScore": "251.07", "maxWeightEstimate": "210-240 KG", "drinkZonesPotential": "06:00-10:00", "animalClass": "6", "maxLevel": "9 (Lendário)" },
    "sambar": { "maxScore": "166.43", "maxWeightEstimate": "270-300 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "cervo_de_timor": { "maxScore": "148.78", "maxWeightEstimate": "145-172 KG", "drinkZonesPotential": "20:00-00:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "gamo": { "maxScore": "249.99", "maxWeightEstimate": "82-100 KG", "drinkZonesPotential": "10:00-13:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "bantengue": { "maxScore": "137", "maxWeightEstimate": "747-800 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "9", "maxLevel": "5 (Médio)" },
    "crocodilo_de_água_salgada": { "maxScore": "1015", "maxWeightEstimate": "856-1100 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "ganso_pega": { "maxScore": "3.85", "maxWeightEstimate": "2-3 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "chital": { "maxScore": "217.29", "maxWeightEstimate": "67-75 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "3", "maxLevel": "5 (Médio)" }
},
"medved_taiga": {
    "alce": { "maxScore": "274.99", "maxWeightEstimate": "545-620 KG", "drinkZonesPotential": "12:00 - 16:00", "animalClass": "8", "maxLevel": "5 (Médio)" },
    "rena_da_montanha": { "maxScore": "430.23", "maxWeightEstimate": "156-182 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "tetraz_grande": { "maxScore": "4.64", "maxWeightEstimate": "4-5 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "cervo_almiscarado": { "maxScore": "249", "maxWeightEstimate": "14-17 KG", "drinkZonesPotential": "08:00 - 12:00", "animalClass": "2", "maxLevel": "3 (Muito Fácil)" },
    "urso_pardo": { "maxScore": "27.7", "maxWeightEstimate": "389-452 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "javali": { "maxScore": "144.25", "maxWeightEstimate": "186-240 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "lince_euroasiática": { "maxScore": "27.68", "maxWeightEstimate": "35-45 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "3", "maxLevel": "9 (Lendário)" },
    "lobo_cinzento": { "maxScore": "39", "maxWeightEstimate": "67-80 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "5", "maxLevel": "9 (Lendário)" }
},
"mississippi_acres": {
    "veado_de_cauda_branca": { "maxScore": "255.09", "maxWeightEstimate": "75-100 KG", "drinkZonesPotential": "08:00 - 12:00", "animalClass": "4", "maxLevel": "3 (Muito Fácil)" },
    "codorniz_da_virgínia": { "maxScore": "238", "maxWeightEstimate": "0 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "marrequinha_americana": { "maxScore": "480", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "peru_selvagem": { "maxScore": "4.6", "maxWeightEstimate": "9-11 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "porco_selvagem": { "maxScore": "144.25", "maxWeightEstimate": "161-205 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "urso_negro": { "maxScore": "22.8", "maxWeightEstimate": "227-290 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "raposa_cinzenta": { "maxScore": "6.43", "maxWeightEstimate": "5-6 KG", "drinkZonesPotential": "17:00 - 20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "guaxinim_comum": { "maxScore": "12", "maxWeightEstimate": "10-13 KG", "drinkZonesPotential": "00:00 - 03:00", "animalClass": "2", "maxLevel": "5 (Médio)" },
    "coelho_da_flórida": { "maxScore": "1.97", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "jacaré_americano": { "maxScore": "492", "maxWeightEstimate": "416-530 KG", "drinkZonesPotential": "08:00 - 12:00, 12:00 - 16:00, 16:00 - 20:00", "animalClass": "7", "maxLevel": "9 (Lendário)" }
},
"new_england_mountains": {
    "alce": { "maxScore": "274.99", "maxWeightEstimate": "545-620 KG", "drinkZonesPotential": "12:00 - 16:00", "animalClass": "8", "maxLevel": "5 (Médio)" },
    "codorniz_da_virgínia": { "maxScore": "238", "maxWeightEstimate": "0 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "coelho_da_flórida": { "maxScore": "1.97", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "faisão_de_pescoço_anelado": { "maxScore": "20.29", "maxWeightEstimate": "2-3 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "marrequinha_americana": { "maxScore": "480", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_olho_de_ouro": { "maxScore": "1230", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_real": { "maxScore": "19.61", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "peru_selvagem": { "maxScore": "4.6", "maxWeightEstimate": "9-11 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "guaxinim_comum": { "maxScore": "12", "maxWeightEstimate": "10-13 KG", "drinkZonesPotential": "03:00 - 06:00", "animalClass": "2", "maxLevel": "5 (Médio)" },
    "lince_pardo": { "maxScore": "27.68", "maxWeightEstimate": "35-45 KG", "drinkZonesPotential": "03:00 - 06:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "raposa_cinzenta": { "maxScore": "6.43", "maxWeightEstimate": "5-6 KG", "drinkZonesPotential": "17:00 - 20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "veado_de_cauda_branca": { "maxScore": "255.09", "maxWeightEstimate": "75-100 KG", "drinkZonesPotential": "08:00 - 12:00", "animalClass": "4", "maxLevel": "3 (Muito Fácil)" },
    "urso_negro": { "maxScore": "22.8", "maxWeightEstimate": "227-290 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "coiote": { "maxScore": "56.87", "maxWeightEstimate": "24-27 KG", "drinkZonesPotential": "00:00 - 04:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "raposa_vermelha": { "maxScore": "14.05", "maxWeightEstimate": "12-15 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" }
},
"parque_fernando": {
    "veado_vermelho": { "maxScore": "251.07", "maxWeightEstimate": "210-240 KG", "drinkZonesPotential": "06:00-10:00", "animalClass": "6", "maxLevel": "9 (Lendário)" },
    "marreca_carijó": { "maxScore": "4.62", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "caititu": { "maxScore": "144.25", "maxWeightEstimate": "26-31 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "veado_mula": { "maxScore": "312.17", "maxWeightEstimate": "175-210 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "onça_parda": { "maxScore": "39", "maxWeightEstimate": "86-105 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "5", "maxLevel": "9 (Lendário)" },
    "antílope_negro": { "maxScore": "132.26", "maxWeightEstimate": "44-51 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "búfalo_dágua": { "maxScore": "167.54", "maxWeightEstimate": "1067-1250 KG", "drinkZonesPotential": "12:00-15:00", "animalClass": "9", "maxLevel": "9 (Lendário)" },
    "chital": { "maxScore": "217.29", "maxWeightEstimate": "67-75 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "3", "maxLevel": "5 (Médio)" }
},
"rancho_del_arroyo": {
    "veado_mula": { "maxScore": "312.17", "maxWeightEstimate": "175-210 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "veado_de_cauda_branca": { "maxScore": "255.09", "maxWeightEstimate": "75-100 KG", "drinkZonesPotential": "08:00 - 12:00", "animalClass": "4", "maxLevel": "3 (Muito Fácil)" },
    "carneiro_selvagem": { "maxScore": "196.93", "maxWeightEstimate": "132-160 KG", "drinkZonesPotential": "12:00-16:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "antilocapra": { "maxScore": "108", "maxWeightEstimate": "57-65 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "caititu": { "maxScore": "144.25", "maxWeightEstimate": "26-31 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "coiote": { "maxScore": "56.87", "maxWeightEstimate": "24-27 KG", "drinkZonesPotential": "09:00 - 00:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "lince_pardo_do_méxico": { "maxScore": "27.68", "maxWeightEstimate": "35-45 KG", "drinkZonesPotential": "03:00 - 06:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "peru_selvagem_do_rio_grande": { "maxScore": "4.62", "maxWeightEstimate": "9-11 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "faisão_de_pescoço_anelado": { "maxScore": "20.29", "maxWeightEstimate": "2-3 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "lebre_antílope": { "maxScore": "6.33", "maxWeightEstimate": "3-4 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" }
},
"salzwiesen": {
    "coelho_europeu": { "maxScore": "2.42", "maxWeightEstimate": "2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "frisada": { "maxScore": "1050", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "galo_lira": { "maxScore": "120", "maxWeightEstimate": "0-1 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "guaxinim_comum": { "maxScore": "12", "maxWeightEstimate": "10-13 KG", "drinkZonesPotential": "00:00 - 03:00", "animalClass": "2", "maxLevel": "5 (Médio)" },
    "raposa_vermelha": { "maxScore": "14.05", "maxWeightEstimate": "12-15 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "ganso_campestre_da_tundra": { "maxScore": "3.16", "maxWeightEstimate": "2-3 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "faisão_de_pescoço_anelado": { "maxScore": "20.29", "maxWeightEstimate": "2-3 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "cão_guaxinim": { "maxScore": "9.29", "maxWeightEstimate": "8-10 kg", "drinkZonesPotential": "10:00-13:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "ganso_bravo": { "maxScore": "3.85", "maxWeightEstimate": "3-4 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "marrequinha_comum": { "maxScore": "354", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_olho_de_ouro": { "maxScore": "1230", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_real": { "maxScore": "19.61", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "piadeira": { "maxScore": "905", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "zarro_negrinha": { "maxScore": "963", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "zarro_castanho": { "maxScore": "1050", "maxWeightEstimate": "0-1 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" }
},
"silver_ridge_peaks": {
    "antilocapra": { "maxScore": "108", "maxWeightEstimate": "57-65 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "carneiro_selvagem": { "maxScore": "196.93", "maxWeightEstimate": "132-160 KG", "drinkZonesPotential": "12:00-16:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "bisão_das_planícies": { "maxScore": "183.5", "maxWeightEstimate": "987-1200 KG", "drinkZonesPotential": "08:00-12:00", "animalClass": "9", "maxLevel": "5 (Médio)" },
    "cabra_da_montanha": { "maxScore": "107.67", "maxWeightEstimate": "120-145 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "veado_mula": { "maxScore": "312.17", "maxWeightEstimate": "175-210 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "onça_parda": { "maxScore": "39", "maxWeightEstimate": "86-105 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "5", "maxLevel": "9 (Lendário)" },
    "urso_negro": { "maxScore": "22.8", "maxWeightEstimate": "227-290 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "veado_das_montanhas_rochosas": { "maxScore": "481.41", "maxWeightEstimate": "410-480 KG", "drinkZonesPotential": "04:00-08:00", "animalClass": "7", "maxLevel": "5 (Médio)" },
    "peru_merriami": { "maxScore": "4.62", "maxWeightEstimate": "9-11 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" }
},
"sundarpatan": {
    "antílope_negro": { "maxScore": "132.26", "maxWeightEstimate": "44-51 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "ganso_bravo": { "maxScore": "3.85", "maxWeightEstimate": "3-4 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "lebre_peluda": { "maxScore": "3.28", "maxWeightEstimate": "2-3 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "muntíaco_vermelho_do_norte": { "maxScore": "35.24", "maxWeightEstimate": "23-28 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "2", "maxLevel": "5 (Médio)" },
    "raposa_tibetana": { "maxScore": "6.37", "maxWeightEstimate": "5-6 kg", "drinkZonesPotential": "17:00-20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "tahr": { "maxScore": "101.87", "maxWeightEstimate": "117-140 KG", "drinkZonesPotential": "04:00-07:00, 07:00-11:00, 14:00-17:00, 17:00-20:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "carneiro_azul": { "maxScore": "154.08", "maxWeightEstimate": "65-75 KG", "drinkZonesPotential": "14:00-17:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "cervo_do_pântano": { "maxScore": "226.05", "maxWeightEstimate": "242-280 KG", "drinkZonesPotential": "12:00-15:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "nilgó": { "maxScore": "94.89", "maxWeightEstimate": "256-308 KG", "drinkZonesPotential": "08:00-12:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "búfalo_dágua": { "maxScore": "167.54", "maxWeightEstimate": "1067-1250 KG", "drinkZonesPotential": "12:00-15:00", "animalClass": "9", "maxLevel": "9 (Lendário)" },
    "leopardo_das_neves": { "maxScore": "29", "maxWeightEstimate": "63-75 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "4", "maxLevel": "9 (Lendário)" },
    "iaque_selvagem": { "maxScore": "273.23", "maxWeightEstimate": "1025-1200 KG", "drinkZonesPotential": "08:00-12:00", "animalClass": "9", "maxLevel": "9 (Lendário)" },
    "tigre_de_bengala": { "maxScore": "57", "maxWeightEstimate": "272-324", "drinkZonesPotential": "04:00-07:00", "animalClass": "9", "maxLevel": "9 (Lendário)" }
},
"te_awaroa": {
    "veado_vermelho": { "maxScore": "251.07", "maxWeightEstimate": "210-240 KG", "drinkZonesPotential": "06:00-10:00", "animalClass": "6", "maxLevel": "9 (Lendário)" },
    "gamo": { "maxScore": "249.99", "maxWeightEstimate": "82-100 KG", "drinkZonesPotential": "10:00-13:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "cabra_selvagem": { "maxScore": "208.71", "maxWeightEstimate": "43-50 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "porco_selvagem": { "maxScore": "144.25", "maxWeightEstimate": "161-205 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "cervo_sika": { "maxScore": "198.74", "maxWeightEstimate": "62-75 KG", "drinkZonesPotential": "10:00-13:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "tahr": { "maxScore": "101.87", "maxWeightEstimate": "117-140 KG", "drinkZonesPotential": "04:00-07:00, 07:00-11:00, 14:00-17:00, 17:00-20:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "peru_merriami": { "maxScore": "4.62", "maxWeightEstimate": "9-11 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "camurça": { "maxScore": "58", "maxWeightEstimate": "57-65 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "coelho_europeu": { "maxScore": "2.42", "maxWeightEstimate": "2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_real": { "maxScore": "19.61", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" }
},
"vurhonga_savanna": {
    "chacal_listrado": { "maxScore": "29.10", "maxWeightEstimate": "12-14 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "lebre_nuca_dourada": { "maxScore": "5.37", "maxWeightEstimate": "4-5 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "piadeira": { "maxScore": "905", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "cudo_menor": { "maxScore": "151.64", "maxWeightEstimate": "91-105 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "cabra_de_leque": { "maxScore": "78.55", "maxWeightEstimate": "38-42 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "javali_africano": { "maxScore": "58.19", "maxWeightEstimate": "123-150 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "gnu_de_cauda_preta": { "maxScore": "37.69", "maxWeightEstimate": "265-290 KG", "drinkZonesPotential": "06:00-09:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "búfalo_africano": { "maxScore": "151.35", "maxWeightEstimate": "802-950 KG", "drinkZonesPotential": "09:00-12:00", "animalClass": "9", "maxLevel": "9 (Lendário)" },
    "leão": { "maxScore": "48.50", "maxWeightEstimate": "236-270 KG", "drinkZonesPotential": "12:00-15:00", "animalClass": "9", "maxLevel": "9 (Lendário)" },
    "órix_do_cabo": { "maxScore": "337.59", "maxWeightEstimate": "210-240 KG", "drinkZonesPotential": "03:00-06:00", "animalClass": "6", "maxLevel": "5 (Médio)" }
},
"yukon_valley": {
    "caribu": { "maxScore": "430.23", "maxWeightEstimate": "161-190KG", "drinkZonesPotential": "04:00-08:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "ganso_do_canadá": { "maxScore": "8.59", "maxWeightEstimate": "8-9 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "alce": { "maxScore": "274.99", "maxWeightEstimate": "545-620 KG", "drinkZonesPotential": "12:00 - 16:00", "animalClass": "8", "maxLevel": "5 (Médio)" },
    "urso_cinzento": { "maxScore": "66.94", "maxWeightEstimate": "551-680 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "8", "maxLevel": "9 (Lendário)" },
    "lobo_cinzento": { "maxScore": "39", "maxWeightEstimate": "67-80 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "5", "maxLevel": "9 (Lendário)" },
    "bisão_das_planícies": { "maxScore": "183.5", "maxWeightEstimate": "987-1200 KG", "drinkZonesPotential": "08:00-12:00", "animalClass": "9", "maxLevel": "5 (Médio)" },
    "raposa_vermelha": { "maxScore": "14.05", "maxWeightEstimate": "12-15 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
    "pato_arlequim": { "maxScore": "7.23", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" }
},
    "askiy_ridge": {
    "alce": { "maxScore": "274.99", "maxWeightEstimate": "545-620 KG", "drinkZonesPotential": "12:00 - 16:00", "animalClass": "8", "maxLevel": "5 (Médio)" },
    "caribu_da_floresta_boreal": { "maxScore": "430.23", "maxWeightEstimate": "161-190 KG", "drinkZonesPotential": "20:00 - 00:00", "animalClass": "6", "maxLevel": "5 (Médio)" },
    "urso_negro": { "maxScore": "22.8", "maxWeightEstimate": "227-290 KG", "drinkZonesPotential": "04:00 - 08:00", "animalClass": "7", "maxLevel": "9 (Lendário)" },
    "veado_mula": { "maxScore": "312.17", "maxWeightEstimate": "175-210 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "bisão_da_floresta": { "maxScore": "158", "maxWeightEstimate": "1112-1350 KG", "drinkZonesPotential": "08:00-12:00", "animalClass": "9", "maxLevel": "5 (Médio)" },
    "cabra_da_montanha": { "maxScore": "107.67", "maxWeightEstimate": "120-145 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "antilocapra": { "maxScore": "108", "maxWeightEstimate": "57-65 KG", "drinkZonesPotential": "18:00-21:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "tetraz_azul": { "maxScore": "151", "maxWeightEstimate": "1.38-1.60 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_real": { "maxScore": "19.61", "maxWeightEstimate": "1-2 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "pato_carolino": { "maxScore": "670", "maxWeightEstimate": "0 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "marreca_arrebio": { "maxScore": "1040", "maxWeightEstimate": "0-1 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "ganso_do_canadá": { "maxScore": "8.59", "maxWeightEstimate": "8-9 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "ganso_das_neves": { "maxScore": "3.85", "maxWeightEstimate": "3-4 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "lobo_cinzento": { "maxScore": "39", "maxWeightEstimate": "67-80 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "5", "maxLevel": "9 (Lendário)" },
    "cervo_canadense": { "maxScore": "457.56", "maxWeightEstimate": "395-450 kg", "drinkZonesPotential": "04:00-08:00", "animalClass": "7", "maxLevel": "5 (Médio)" },
    "veado_de_cauda_branca": { "maxScore": "255.09", "maxWeightEstimate": "75-100 KG", "drinkZonesPotential": "08:00 - 12:00", "animalClass": "4", "maxLevel": "3 (Muito Fácil)" },
    "faisão_de_pescoço_anelado": { "maxScore": "20.29", "maxWeightEstimate": "2-3 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "carneiro_selvagem": { "maxScore": "196.93", "maxWeightEstimate": "132-160 KG", "drinkZonesPotential": "12:00-16:00", "animalClass": "5", "maxLevel": "5 (Médio)" },
    "castor_norte_americano": { "maxScore": "30.40", "maxWeightEstimate": "28-32 kg", "drinkZonesPotential": "04:00-08:00, 08:00-12:00, 16:00-20:00", "animalClass": "2", "maxLevel": "5 (Médio)" }
},
"torr_nan_sithean": {
    "veado_vermelho": { "maxScore": "251.07", "maxWeightEstimate": "210-240 KG", "drinkZonesPotential": "06:00-10:00", "animalClass": "6", "maxLevel": "9 (Lendário)" },
    "gamo": { "maxScore": "249.99", "maxWeightEstimate": "82-100 KG", "drinkZonesPotential": "10:00-13:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "cabra_selvagem": { "maxScore": "208.71", "maxWeightEstimate": "43-50 KG", "drinkZonesPotential": "15:00-18:00", "animalClass": "3", "maxLevel": "5 (Médio)" },
    "javali": { "maxScore": "144.25", "maxWeightEstimate": "186-240 KG", "drinkZonesPotential": "00:00-03:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "cervo_sika": { "maxScore": "198.74", "maxWeightEstimate": "62-75 KG", "drinkZonesPotential": "10:00-13:00", "animalClass": "4", "maxLevel": "5 (Médio)" },
    "piadeira": { "maxScore": "905", "maxWeightEstimate": "0 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "faisão_de_pescoço_anelado": { maxScore: "20.29", maxWeightEstimate: "2-3 kg", drinkZonesPotential: "O DIA TODO", animalClass: "1", maxLevel: "3 (Muito Fácil)" },
    "tetraz_vermelho": { "maxScore": "72.75", "maxWeightEstimate": "0-0.64 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "galinhola_eurasiática": { "maxScore": "41.03", "maxWeightEstimate": "0-0.25 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "vison_americano": { "maxScore": "151", "maxWeightEstimate": "0.7-1.60 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
   "marta_europeia": { "maxScore": "208", "maxWeightEstimate": "1-2.20 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
   "texugo_europeu": { "maxScore": "16", "maxWeightEstimate": "0-12.83 KG", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "5 (Médio)" },
    "galo_lira": { "maxScore": "120", "maxWeightEstimate": "0-1 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
    "lebre_da_eurásia": { "maxScore": "5.6", "maxWeightEstimate": "5-6 kg", "drinkZonesPotential": "O DIA TODO", "animalClass": "1", "maxLevel": "3 (Muito Fácil)" },
"corça": { "maxScore": "81.86", "maxWeightEstimate": "29-35 KG", "drinkZonesPotential": "14:00-17:00", "animalClass": "3", "maxLevel": "3 (Muito Fácil)" },
"raposa_vermelha": { "maxScore": "14.05", "maxWeightEstimate": "12-15 KG", "drinkZonesPotential": "17:00-20:00", "animalClass": "2", "maxLevel": "9 (Lendário)" },
},
};

export const multiMountsData = { "a_fuga": { name: "A Fuga", animals: [{ slug: "veado_vermelho", gender: "macho" },{ slug: "veado_vermelho", gender: "femea" }] }, "abraco_do_urso": { name: "Abraço do Urso", animals: [{ slug: "urso_cinzento", gender: "macho" },{ slug: "urso_cinzento", gender: "macho" }] }, "adeus_filho": { name: "Adeus, Filho", animals: [{ slug: "bisão_das_planícies", gender: "macho" },{ slug: "lobo_cinzento", gender: "macho" },{ slug: "lobo_cinzento", gender: "macho" }] }, "admiralces": { name: "Admiralces", animals: [{ slug: "alce", gender: "macho" },{ slug: "codorniz_da_virgínia", gender: "macho" }] }, "almoco_da_raposa": { name: "Almoço da Raposa", animals: [{ slug: "raposa_vermelha", gender: "macho" },{ slug: "lebre_da_cauda_branca", gender: "macho" }] }, "banquete_no_ar": { name: "Banquete no Ar", animals: [{ slug: "raposa_vermelha", gender: "macho" },{ slug: "faisão_de_pescoço_anelado", gender: "macho" }] }, "brincadeira_de_aves": { name: "Brincadeira de Aves", animals: [{ slug: "lagópode_escocês", gender: "macho" },{ slug: "cão_guaxinim", gender: "macho" }] }, "brincando_de_briga": { name: "Brincando de Briga", animals: [{ slug: "lince_euroasiática", gender: "macho" },{ slug: "lince_euroasiática", gender: "femea" }] }, "caudas_brancas_unidas": { name: "Caudas Brancas Unidas", animals: [{ slug: "veado_de_cauda_branca", gender: "macho" },{ slug: "veado_de_cauda_branca", gender: "macho" },{ slug: "veado_de_cauda_branca", gender: "macho" }] }, "colisao": { name: "Colisão", animals: [{ slug: "veado_de_cauda_preta", gender: "macho" },{ slug: "onça_parda", gender: "macho" }] }, "competicao_amistosa": { name: "Competição Amistosa", animals: [{ slug: "coiote", gender: "macho" },{ slug: "coiote", gender: "macho" },{ slug: "lebre_da_cauda_branca", gender: "macho" }] }, "corcas_unidas": { name: "Corças Unidas", animals: [{ slug: "corça", gender: "macho" },{ slug: "corça", gender: "macho" },{ slug: "corça", gender: "macho" }] }, "davi_e_golias": { name: "Davi e Golias", animals: [{ slug: "ganso_do_canadá", gender: "macho" },{ slug: "bisão_europeu", gender: "macho" }] }, "de_cabeca": { name: "De Cabeça", animals: [{ slug: "ibex_de_beceite", gender: "macho" },{ slug: "ibex_de_gredos", gender: "macho" }] }, "decolagem_de_emergencia": { name: "Decolagem de Emergência", animals: [{ slug: "coiote", gender: "macho" },{ slug: "pato_real", gender: "macho" },{ slug: "pato_real", gender: "macho" },{ slug: "pato_real", gender: "femea" }] }, "despedida_do_solteiros": { name: "Despedida dos Solteiros", animals: [{ slug: "veado_mula", gender: "macho" },{ slug: "veado_mula", gender: "femea" },{ slug: "veado_mula", gender: "femea" }] }, "dois_tipos_de_perus": { name: "Dois Tipos de Perus", animals: [{ slug: "peru_selvagem", gender: "macho" },{ slug: "peru_selvagem_do_rio_grande", gender: "macho" }] }, "espionagem_tatica": { name: "Espionagem Tática", animals: [{ slug: "onça_parda", gender: "femea" },{ slug: "veado_de_roosevelt", gender: "macho" }] }, "faisoes_em_fuga": { name: "Faisões em Fuga", animals: [{ slug: "faisão_de_pescoço_anelado", gender: "macho" },{ slug: "faisão_de_pescoço_anelado", gender: "macho" }] }, "falso_tronco": { name: "Falso Tronco", animals: [{ slug: "jacaré_americano", gender: "macho" },{ slug: "guaxinim_comum", gender: "macho" }] }, "fantasma_da_montanha": { name: "Fantasma da Montanha", animals: [{ slug: "leopardo_das_neves", gender: "macho" },{ slug: "carneiro_azul", gender: "macho" }] }, "fartura_de_bisoes": { name: "Fartura de Bisões", animals: [{ slug: "bisão_europeu", gender: "macho" },{ slug: "bisão_europeu", gender: "macho" }] }, "gamos_unidos": { name: "Gamos Unidos", animals: [{ slug: "gamo", gender: "macho" },{ slug: "gamo", gender: "macho" },{ slug: "gamo", gender: "macho" }] }, "ganha_pao": { name: "Ganha-pão", animals: [{ slug: "búfalo_africano", gender: "macho" },{ slug: "leão", gender: "macho" },{ slug: "leão", gender: "femea" },{ slug: "leão", gender: "femea" }] }, "gansos_zangados": { name: "Gansos Zangados", animals: [{ slug: "ganso_do_canadá", gender: "macho" },{ slug: "ganso_do_canadá", gender: "macho" }] }, "gluglu": { name: "Gluglu", animals: [{ slug: "peru_selvagem", gender: "macho" },{ slug: "peru_selvagem", gender: "femea" },{ slug: "peru_selvagem", gender: "femea" }] }, "lanchinho_de_tigre": { name: "Lanchinho de Tigre", animals: [{ slug: "tahr", gender: "macho" },{ slug: "tahr", gender: "femea" },{ slug: "tahr", gender: "femea" }] }, "laod_a_lado": { name: "Lado a Lado", animals: [{ slug: "veado_de_cauda_branca", gender: "macho" },{ slug: "veado_de_cauda_branca", gender: "macho" }] }, "lebres_rivais": { name: "Lebres Rivais", animals: [{ slug: "lebre_antílope", gender: "macho" },{ slug: "lebre_antílope", gender: "macho" }] }, "lobo_alfa": { name: "Lobo Alfa", animals: [{ slug: "lobo_cinzento", gender: "macho" },{ slug: "lobo_cinzento", gender: "femea" },{ slug: "lobo_cinzento", gender: "femea" }] }, "marujos_de_agua_doce": { name: "Marujos de Água Doce", animals: [{ slug: "faisão_de_pescoço_anelado", gender: "macho" },{ slug: "tetraz_grande", gender: "macho" },{ slug: "ganso_bravo", gender: "macho" },{ slug: "ganso_campestre_da_tundra", gender: "macho" }] }, "necessidades_basicas": { name: "Necessidades Básicas", animals: [{ slug: "urso_negro", gender: "macho" },{ slug: "urso_negro", gender: "macho" }] }, "o_grand_slam": { name: "O Grand Slam", animals: [{ slug: "ibex_de_beceite", gender: "macho" },{ slug: "ibex_de_gredos", gender: "macho" },{ slug: "ibex_de_ronda", gender: "macho" },{ slug: "ibex_espanhol_do_sudeste", gender: "macho" }] }, "operador_suave": { name: "Operador Suave", animals: [{ slug: "tetraz_grande", gender: "macho" },{ slug: "tetraz_grande", gender: "femea" },{ slug: "tetraz_grande", gender: "femea" }] }, "os_tres_patinhos": { name: "Os Três Patinhos", animals: [{ slug: "piadeira", gender: "macho" },{ slug: "zarro_castanho", gender: "macho" },{ slug: "frisada", gender: "macho" }] }, "parceiros_no_crime": { name: "Parceiros no Crime", animals: [{ slug: "raposa_vermelha", gender: "macho" },{ slug: "raposa_vermelha", gender: "macho" }] }, "presas_a_mostra": { name: "Presas à Mostra", animals: [{ slug: "mouflão_ibérico", gender: "macho" },{ slug: "lobo_ibérico", gender: "macho" },{ slug: "lobo_ibérico", gender: "macho" },{ slug: "lobo_ibérico", gender: "macho" }] }, "procos_do_mato_em_conflito": { name: "Procos-do-Mato em Conflito", animals: [{ slug: "caititu", gender: "macho" },{ slug: "caititu", gender: "macho" }] }, "ramboru": { name: "Ramboru", animals: [{ slug: "canguru_cinza_oriental", gender: "macho" },{ slug: "canguru_cinza_oriental", gender: "macho" }] }, "raposas_adversarias": { name: "Raposas Adversárias", animals: [{ slug: "raposa_vermelha", gender: "macho" },{ slug: "raposa_cinzenta", gender: "macho" }] }, "realeza": { name: "Realeza", animals: [{ slug: "leão", gender: "macho" },{ slug: "leão", gender: "femea" }] }, "rixa_de_aves": { name: "Rixa de Aves", animals: [{ slug: "galo_lira", gender: "macho" },{ slug: "galo_lira", gender: "macho" }] }, "saindo_de_fininho": { name: "Saindo de Fininho", animals: [{ slug: "pato_real", gender: "macho" },{ slug: "pato_olho_de_ouro", gender: "macho" },{ slug: "zarro_negrinha", gender: "macho" },{ slug: "marrequinha_comum", gender: "macho" },{ slug: "piadeira", gender: "macho" },{ slug: "zarro_castanho", gender: "macho" },{ slug: "frisada", gender: "macho" }] }, "tahr_angulo_amoroso": { name: "Tahr-ângulo Amoroso", animals: [{ slug: "tigre_de_bengala", gender: "macho" },{ slug: "cervo_do_pântano", gender: "macho" }] }, "treno_vendido_separadamente": { name: "Trenó Vendido Separadamente", animals: [{ slug: "rena_da_montanha", gender: "macho" },{ slug: "rena_da_montanha", gender: "macho" },{ slug: "rena_da_montanha", gender: "macho" }] }, "turma_dos_coelhos": { name: "Turma dos Coelhos", animals: [{ slug: "lebre_da_cauda_branca", gender: "macho" },{ slug: "lebre_da_cauda_branca", gender: "macho" },{ slug: "lebre_da_cauda_branca", gender: "femea" },{ slug: "lebre_da_cauda_branca", gender: "femea" }] }, "um_crocodilo_sortudo": { name: "Um Crocodilo Sortudo", animals: [{ slug: "ganso_pega", gender: "macho" },{ slug: "crocodilo_de_água_salgada", gender: "macho" }] }, "um_par_de_predadores": { name: "Um Par de Predadores", animals: [{ slug: "coiote", gender: "macho" },{ slug: "lince_pardo_do_méxico", gender: "macho" }] }, "vigilancia": { name: "Vigilância", animals: [{ slug: "cudo_menor", gender: "macho" },{ slug: "cudo_menor", gender: "femea" }] }, "viver_amar_lenhar": { name: "Viver, Amar, Lenhar", animals: [{ slug: "castor_norte_americano", gender: "macho" },{ slug: "castor_norte_americano", gender: "femea" }] } };
